create table if not exists staging.stg_races (
    season number,
    round_number number,
    race_name string,
    race_date date,
    race_time string,
    circuit_id string,
    fp1_date date,
    fp1_time string,
    fp2_date date,
    fp2_time string,
    fp3_date date,
    fp3_time string,
    qualifying_date date,
    qualifying_time string,
    sprint_date date,
    sprint_time string,
    sprint_qualifying_date date,
    sprint_qualifying_time string,
    profile_url string,
    ingested_at timestamp_ntz default current_timestamp()
);